package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_order", "order_id", Order.class);
		arp.addMapping("t_orderitem", "orderitem_id", Orderitem.class);
		arp.addMapping("t_product", "product_id", Product.class);
		arp.addMapping("t_user", "user_id", User.class);
	}
}

