package com.demo.common.model;

import com.demo.common.model.base.BaseOrderitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orderitem extends BaseOrderitem<Orderitem> {
	
}
