package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderitem<M extends BaseOrderitem<M>> extends Model<M> implements IBean {

	public void setOrderitemId(java.lang.Integer orderitemId) {
		set("orderitem_id", orderitemId);
	}
	
	public java.lang.Integer getOrderitemId() {
		return getInt("orderitem_id");
	}

	public void setOrderitemPid(java.lang.Integer orderitemPid) {
		set("orderitem_pid", orderitemPid);
	}
	
	public java.lang.Integer getOrderitemPid() {
		return getInt("orderitem_pid");
	}

	public void setOrderitemNum(java.lang.Integer orderitemNum) {
		set("orderitem_num", orderitemNum);
	}
	
	public java.lang.Integer getOrderitemNum() {
		return getInt("orderitem_num");
	}

	public void setOrderitemOid(java.lang.Integer orderitemOid) {
		set("orderitem_oid", orderitemOid);
	}
	
	public java.lang.Integer getOrderitemOid() {
		return getInt("orderitem_oid");
	}

}
