package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}
	
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public void setProductPrice(java.lang.Float productPrice) {
		set("product_price", productPrice);
	}
	
	public java.lang.Float getProductPrice() {
		return getFloat("product_price");
	}

}
